[package]
name = "anylm"
version = "0.4.0"
description = "The universal API for all AI services that you know"
keywords = ["lm", "api", "ai", "llm", "slm"]
categories = ["development-tools", "rust-patterns"]
license = "MIT"
authors = ["Bulat Sh. <t.me/fuderis>"]
repository = "https://github.com/fuderis/anylm-rs"
readme = "README.md"
edition = "2024"

[workspace]
members = ["crates/schema"]
default-members = ["crates/schema"]
resolver = "3"

[workspace.dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.39"
syn = { version = "2.0.100", features = ["full", "parsing", "extra-traits"] }
heck = "0.4"

[dependencies]
anylm-schema = { version = "0.1.0", optional = true }

atoman = { version = "0.11.8", features = ["channel"] }
macron = { version = "0.5.1", features = ["derive", "string"] }
pearce = { version = "0.6.0", features = ["stream", "client"] }

# pearce = { path = "../pearce", features = ["stream", "client"] }

base64 = "0.22.1"
bytes = "1.11.1"
chrono = { version = "0.4.44", features = ["serde"] }
futures = "0.3.31"
regex = "1.12.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tiktoken-rs = "0.9.1"

[features]
default = ["rustls"]

rustls = ["pearce/rustls"]
native-tls = ["pearce/native-tls"]

full = ["derive", "anthropic", "google", "rustls"]
derive = ["anylm-schema"]
anthropic = []
google = []
